apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

meatdata:
	    name: expense
   		region: us-east-1
		
manageNodeGroups:
	  - name: expense 
	    instanceType: m5.large
		  desiredCapacity: 3
		  spot: true 